name: 'ci-action'
description: 'Continious Integration action for go- and node- projects'
inputs:
  ignore:
    description: Folders and files that will be ignored when checking (comma separated)
    required: false
  organization:
    description: The name of the organization on GitHub containing private repositories
    default: untillpro
  token:
    description: Auth token used to fetch dependencies from private repositories
  codecov-token:
    description: Codecov token
  publish-asset:
    description: File / dir name to publish
  publish-token:
    description: Auth token used to publish
    default: ${{ github.token }}
  publish-keep:
    description: Number of kept releases (0 - all)
    default: 8
  repository:
    description: 'Repository name with owner. For example, untillpro/ci-action'
    default: ${{ github.repository }}
runs:
  using: 'node12'
  main: 'dist/index.js'
