name: CI-Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Checkout
      uses: actions/checkout@v2
    - name: CI
      uses: ./
      with:
        ignore: dist
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
        publish-asset: ci-action.exe
      env:
        GOOS: windows
        GOARCH: 386
